name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    # - cron: "30 18 * * *"
    - cron: "0 */5 * * *" # “At minute 0 past every 2nd hour.”

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      # - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      - uses: fidellim/waka-readme-stats@show_total_time
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "💥 Update README with Wakatime and Other GitHub Stats 💥"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 1
